version: "3.9"

services:
  postgres_db:
    container_name: "postgres_db"
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5480:5432"

  tgbot:
    # Need update
    container_name: "tgbot"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - uraraka_database
    env_file:
      - ./.env