version: "3.9"

services:
  postgres_db:
    container_name: "postgres_db"
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5480:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    container_name: "alembic_migration"
    build:
      context: .
      dockerfile: web/Dockerfile
    command: /bin/sh -c "sleep 5 && alembic upgrade head"
    volumes:
      - ./web:/app/web
      - ./database:/app/database
      - ./migration:/app/migration
    env_file:
      - ./.env
    depends_on:
      - postgres_db

  tgbot:
    container_name: "tgbot"
    build:
      context: .
      dockerfile: bot_src/Dockerfile
    volumes:
      - ./bot_src:/app/bot_src
      - ./database:/app/database
      - ./migration:/app/migration
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - postgres_db
      - migrate

  web_app:
    container_name: "web_app"
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
      - ./web:/app/web
      - ./database:/app/database
      - ./migration:/app/migration
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres_db
      - migrate

volumes:
  pgdata: