"""Added trigger for stages on delete

Revision ID: 21c36f1c894d
Revises: ee6171ef8d12
Create Date: 2025-05-11 16:06:14.379625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.models.triggers import fix_event_number_on_delete_trigger

# revision identifiers, used by Alembic.
revision: str = '21c36f1c894d'
down_revision: Union[str, None] = 'ee6171ef8d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'onboardings', ['name'])
    for command in fix_event_number_on_delete_trigger['upgrade']:
        op.execute(command)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboardings', type_='unique')
    for command in fix_event_number_on_delete_trigger['downgrade']:
        op.execute(command)
    # ### end Alembic commands ###
