"""Removed answe_text param in UserStage table

Revision ID: 504c0a15e3d5
Revises: d2420435aceb
Create Date: 2025-05-10 12:40:16.177020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504c0a15e3d5'
down_revision: Union[str, None] = 'd2420435aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stages', 'answer_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stages', sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
