"""Create new trigger for fix event number on update

Revision ID: 6cc7e7a42fa8
Revises: 21c36f1c894d
Create Date: 2025-05-14 14:06:34.455762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.models.triggers import fix_event_number_on_update_trigger

# revision identifiers, used by Alembic.
revision: str = '6cc7e7a42fa8'
down_revision: Union[str, None] = '21c36f1c894d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for command in fix_event_number_on_update_trigger['upgrade']:
        op.execute(command)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for command in fix_event_number_on_update_trigger['downgrade']:
        op.execute(command)
    # ### end Alembic commands ###
