"""Add Onboarding table

Revision ID: 74126203a837
Revises: d8acaf22545b
Create Date: 2025-05-08 18:29:56.171829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74126203a837'
down_revision: Union[str, None] = 'd8acaf22545b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboardings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_message_unauthorized', sa.Text(), nullable=False),
    sa.Column('start_message_authorized', sa.Text(), nullable=False),
    sa.Column('phone_request', sa.Text(), nullable=False),
    sa.Column('invalid_phone', sa.Text(), nullable=False),
    sa.Column('fullname_request', sa.Text(), nullable=False),
    sa.Column('invalid_fullname', sa.Text(), nullable=False),
    sa.Column('email_request', sa.Text(), nullable=False),
    sa.Column('invalid_email', sa.Text(), nullable=False),
    sa.Column('speciality_request', sa.Text(), nullable=False),
    sa.Column('invalid_speciality', sa.Text(), nullable=False),
    sa.Column('success_registration', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stages', sa.Column('mid_message', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'mid_message')
    op.drop_table('onboardings')
    # ### end Alembic commands ###
