"""Add is_active in Onboarding table

Revision ID: ee6171ef8d12
Revises: 504c0a15e3d5
Create Date: 2025-05-11 15:04:13.386059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.models.triggers import ensure_single_active_onboarding_trigger

# revision identifiers, used by Alembic.
revision: str = 'ee6171ef8d12'
down_revision: Union[str, None] = '504c0a15e3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('onboardings', sa.Column('name', sa.Text(), nullable=False))
    for command in ensure_single_active_onboarding_trigger['upgrade']:
        op.execute(command)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboardings', 'is_active')
    op.drop_column('onboardings', 'name')
    for command in ensure_single_active_onboarding_trigger['downgrade']:
        op.execute(command)
    # ### end Alembic commands ###
